name: PyPI release

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build setuptools twine

    - name: Build and upload tasmota-metrics ${{ github.event.release.tag_name }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PROJECT_TOKEN }}
      run: |
        PUBLISHED_VERSION=$(curl https://pypi.org/pypi/tasmota-metrics/json 2>/dev/null | jq -r '.info.version')
        CURRENT_VERSION=$(python setup.py --version 2>/dev/null)
        if [ "$PUBLISHED_VERSION" == "$CURRENT_VERSION" ]; then
          echo "Version ${PUBLISHED_VERSION} already published, skipping..."
          exit 0
        else
          echo "Packaging and publishing new tasmota-metrics version: ${CURRENT_VERSION}"
          python -m build
          twine check dist/* && twine upload dist/*
        fi
